feat(MainMethodChecker): support new main method formats
uni-passau-artemis/pipeline-helper pull request #18
Opened 2024-09-04 09:01 UTC by BaumiCoder

A method is a main method if it has the following properties:

1. Its name is `main`.
2. It has no parameter or one String Array parameter.
3. Its return type is `void`
4. It is not `private`.

Only classes with one such method are selected as classes with a main method.

Closes #3

2024-09-04 09:03 UTC, BaumiCoder commented
To work on a Java project, which is compiled with Java 23, the helper also needs to be compiled with Java 23. Should we upgrade the Java version in the `pom.xml` already to 23, because of this?

2024-09-04 09:30 UTC, b-fein commented
> To work on a Java project, which is compiled with Java 23, the helper also needs to be compiled with Java 23.

Does it really? I think as long as it *runs* on a JVM 23 the classloader should also be able to load the classes for reflection at runtime even if the classes of the pipeline helper itself have been compiled to target Java 17.

https://github.com/uni-passau-artemis/pipeline-helper/blob/eb40195905a3d01ef81ed81fdce27867ec18c37b/src/main/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodChecker.java#L73

---

Can you add a few Java example files and tests for them to showcase which `main` method is expected to be found? E.g. public/protected/package-private methods, with/without argument, instance/static method, `main` method in superclass/interface.

The `MainMethodCheckerTest` has some examples. Since you have more variants now, you might have to create the various test classes in sub-packages and then restrict the test to search only in those subpackages of `target/test-classes/`.

2024-09-04 09:35 UTC, b-fein commented
Potentially special edge case that should be checked in tests:

What happens in case there are multiple `main` methods in a single class as in the example below? The code of the checker handles `filesWithMainMethods`. Does this still report an error in case there are multiple?

```java
/// We are now allowed to have multiple valid `main` methods in a class due to different parameter overloads.
class MultiMain {
    void main() {
        System.out.println("main1");
    }

    void main(String[] args) {
        System.out.println("main overloaded");
    }
}
```

I know that the JEP specifies that in such cases there is an ordering and one specific one is selected, but I think as simplification for our case it would be enough to check that there is *any* unique `main` method.

2024-09-05 08:18 UTC, BaumiCoder commented
> Does it really? I think as long as it _runs_ on a JVM 23 the classloader should also be able to load the classes for reflection at runtime even if the classes of the pipeline helper itself have been compiled to target Java 17.

You are right. Compiling with Java 17 and running with Java 23 works. (The only way to do so seems to be outside an IDE. Using pipeline-helper-2.1.0-**shaded**.jar for the `classpath` to have all dependencies.)

2024-09-05 08:56 UTC, BaumiCoder commented
> The `MainMethodCheckerTest` has some examples. Since you have more variants now, you might have to create the various test classes in sub-packages and then restrict the test to search only in those subpackages of `target/test-classes/`.

Restricting the class path does not work properly. The [getClassName](https://github.com/uni-passau-artemis/pipeline-helper/blob/4df2eba79ad2536d1bbc6ece53218ff61ec97471/src/main/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodChecker.java#L84) Method only gives you a name like `PublicStaticNoParam` instead of ` de.uni_passau.fim.se2.pipeline_helper.checkers.MainMethodExamples.PublicStaticNoParam`, which is necessary for the [loadClass](https://github.com/uni-passau-artemis/pipeline-helper/blob/4df2eba79ad2536d1bbc6ece53218ff61ec97471/src/main/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodChecker.java#L92) method.

I will remove the main methods in the Test class itself. Therefore, no other classes with main methods are in the testing source code and a filtering is not necessary anymore.

2024-09-05 17:36 UTC, b-fein reviewed
Thanks for adding the tests, those look good. I have two more questions/suggestions, though.

2024-09-05 17:36 UTC, b-fein commented on src/test/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodExamples/invalid/MultipleValidMethods.java
Why is this part of the `invalid` package? As far as I understand this is a valid definition of a Main class according to the JEP that should however be flagged by the Checker:
We want to show this as not allowed to the user since from a didactic perspective we want to teach to students that they should uniquely mark the `main` method without having to rely on the correct selection based on some internal JVM startup logic.

Sorry for not being clear enough about the intention in my previous comment https://github.com/uni-passau-artemis/pipeline-helper/pull/18#issuecomment-2328380115.

2024-09-05 17:36 UTC, b-fein commented on src/test/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodExamples/package-info.java
`MainMethodExamples`: Java packages usually follow a camel-case naming convention.

2024-09-06 08:20 UTC, BaumiCoder commented on src/test/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodExamples/package-info.java
Addressed with 16aa6fd6f78c8298fc3f1f21ab2a33e5fd2e4ef8

2024-09-06 08:41 UTC, BaumiCoder commented on src/test/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodExamples/invalid/MultipleValidMethods.java
Thus, more than one main method (in one or more classes) should lead to an error (i.e. `CheckerResult.getSuccess()` returns false). Now I understand your target.

How to show this in the output? The message `Found multiple main methods` would be also correct here, but listing the class names is not enough, especially with only one class but multiple main methods in it. Maybe adding some postfix for multiple main methods in one class (e.g. ` (x2)` for two main methods in a class) gives some clarity. What do you think?

2024-09-06 08:43 UTC, b-fein commented on src/test/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodExamples/invalid/MultipleValidMethods.java
> postfix for multiple main methods in one class, e.g. (x2)

Sounds good

2024-09-06 09:43 UTC, BaumiCoder commented on src/test/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodExamples/package-info.java
I changed it to snake_case with https://github.com/uni-passau-artemis/pipeline-helper/pull/18/commits/497b9358c8392f07b1e502a5e62f1d699c22f41e.

2024-09-06 09:45 UTC, BaumiCoder commented on src/test/java/de/uni_passau/fim/se2/pipeline_helper/checkers/MainMethodExamples/invalid/MultipleValidMethods.java
I implemented this in the checker with e30b83d4fbdc97b7116f6cb5d12ece018b0ca3d7 and adjusted the test with 24b60a5bdf1ca79c1c13eeb5f9566a5816cb3493.

2024-09-12 07:24 UTC, b-fein requested changes
Additional discussion yesterday:

Can the JVM start with `Sub1` or `Sub2` as main classes in the following examples? If so, does the tool correctly identify if one or multiple main methods exist? 

What happens in case the is an abstract class with a `protected` main method and two subclasses exist that do not override this method?
```java
class AbstractSuper {
    protected void main() {
        System.out.println("Using main from abstract superclass");
    }
}

class Sub1 extends AbstractSuper {}

class Sub2 extends AbstractSuper {}
```

What happens to abstract main methods?
```java
class AbstractSuper {
    abstract void main();
}

class Sub1 extends AbstractSuper {
    void main() {
        System.out.println("Only valid main method -> okay");
    }
}
```

Main methods in an interface with default implementations?
```java
interface HasMain {
    default void main() {
        System.out.println("main method in interface");
    }
}

class Sub1 implements HasMain {}
```

2024-09-12 09:00 UTC, BaumiCoder commented
> What happens in case the is an class with a `protected` main method and two subclasses exist that do not override this method? What happens in case the method is overridden?
> 
> ```java
> class SuperClass {
>     protected void main() {
>         System.out.println("Using main from abstract superclass");
>     }
> }
> 
> class Sub1 extends SuperClass {}
> 
> class Sub2 extends SuperClass {}
> ```

SuperClass, Sub1 and Sub2 can be executed, but the helper cannot find Sub1 and Sub2. The problem is that [getDeclaredMethods()](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#getDeclaredMethods()) does not return inherited methods and [getMethods()](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#getMethods()) include inherited methods, but only return the `public` methods of a class. Using both methods would at least add a support for inherited `public` methods, but inherited method which are `protected` or package private cannot be found with this approach. The only possible way I found is to use [getSuperclass()](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#getSuperclass()) to go up inheritance hierarchy to be able to call `getDeclaredMethods()` on all Superclasses. Is there a better way to solve this?

> What happens to abstract main methods?
> 
> ```java
> abstract class AbstractSuper {
>     abstract void main();
> }
> 
> class Sub1 extends AbstractSuper {
>     void main() {
>         System.out.println("Only valid main method -> okay");
>     }
> }
> ```

AbstractSuper cannot be executed, but the helper founds it. Fixed with 7d89b71b78f9ad48a510afb67758ead616b886ae.

> Main methods in an interface with default implementations?
> 
> ```java
> interface HasMain {
>     default void main() {
>         System.out.println("main method in interface");
>     }
> }
> 
> class Sub1 implements HasMain {}
> ```

Sub1 can be executed and the interface not, but the helper cannot find any of them. Facing with the same problem as for the SuperClass situation.

2024-10-01 08:14 UTC, b-fein approved these changes
As discussed today: Can be merged.

Code looks good, too.

2024-10-01 08:20 UTC, merged